#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/blinkdesk/blinkdesk /usr/bin/blinkdesk

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/blinkdesk.service ]; then
			rm /etc/systemd/system/blinkdesk.service /usr/lib/systemd/system/blinkdesk.service /usr/lib/systemd/user/blinkdesk.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/blinkdesk/files/systemd/blinkdesk.service /usr/lib/systemd/system/blinkdesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload blinkdesk.service: Unit blinkdesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/blinkdesk.service:10: Executable path is not absolute: pkill -f "blinkdesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/blinkdesk.service
		fi
		systemctl daemon-reload
		systemctl enable blinkdesk
		systemctl start blinkdesk
	fi
fi
